const express=require('express');
const cors=require('cors');
const dotenv=require('dotenv');
dotenv.config();
const db=require('./config/db');
const auth=require('./controllers/authController');
const keys=require('./controllers/keyController');
const {requireJwt}=require('./middleware/auth');
const usage=require('./controllers/usageController');
const publicApi=require('./routes/api');
const app=express();
app.set('trust proxy',1);
app.use(cors({origin:process.env.CORS_ORIGIN||'*'}));
app.use(express.json({limit:'1mb'}));
app.use(express.static('public'));
app.get('/',(req,res)=>res.json({name:'Wisata API SaaS',version:'1.0.0',status:'ok',docs:'/docs'}));
app.get('/health',async(req,res)=>{ try{await db.query('SELECT 1');res.json({status:'ok',database:'connected'});}catch(e){res.status(503).json({status:'degraded',database:'unavailable'});} });
app.get('/docs',(req,res)=>res.sendFile(require('path').join(__dirname,'../public/docs.html')));
app.get('/dashboard',(req,res)=>res.sendFile(require('path').join(__dirname,'../public/dashboard.html')));
app.post('/api/auth/register',auth.register);
app.post('/api/auth/login',auth.login);
app.get('/api/auth/me',requireJwt,auth.me);
app.get('/api/keys',requireJwt,keys.list);
app.post('/api/keys',requireJwt,keys.create);
app.patch('/api/keys/:id/revoke',requireJwt,keys.revoke);
app.get('/api/usage',requireJwt,usage.summary);
app.use('/v1',publicApi);
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:'Internal server error'});});
module.exports=app;
